# GoReleaser configuration for gimage
# Documentation: https://goreleaser.com

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

# Metadata about the project
project_name: gimage

# Before hooks - run before building
before:
  hooks:
    # Clean up before building
    - go mod tidy
    # Run tests to ensure everything works
    - go test -short ./...

# Build configuration
builds:
  # Main CLI binary
  - id: gimage
    main: ./cmd/gimage
    binary: gimage

    # Build flags
    ldflags:
      # Inject version at build time
      # -s = strip debug info, -w = omit DWARF symbol table (smaller binaries)
      - -s -w
      - -X github.com/apresai/gimage/internal/cli.version={{.Version}}

    # Platforms to build for
    goos:
      - linux
      - darwin    # macOS
      - windows

    goarch:
      - amd64     # Intel/AMD 64-bit
      - arm64     # ARM 64-bit (Apple Silicon, AWS Graviton)

    # Skip certain combinations that don't make sense
    ignore:
      - goos: windows
        goarch: arm64  # Windows ARM64 not commonly used yet

    # Environment variables for build
    env:
      - CGO_ENABLED=0  # Pure Go, no C dependencies

  # Deployment manager binary
  - id: gimage-deploy
    main: ./gimage-deploy/cmd/gimage-deploy
    binary: gimage-deploy

    # Build flags
    ldflags:
      - -s -w
      - -X github.com/apresai/gimage/gimage-deploy/internal/version.Version={{.Version}}

    # Platforms to build for
    goos:
      - linux
      - darwin    # macOS
      - windows

    goarch:
      - amd64     # Intel/AMD 64-bit
      - arm64     # ARM 64-bit (Apple Silicon, AWS Graviton)

    # Skip certain combinations that don't make sense
    ignore:
      - goos: windows
        goarch: arm64  # Windows ARM64 not commonly used yet

    # Environment variables for build
    env:
      - CGO_ENABLED=0  # Pure Go, no C dependencies

# Archive configuration - how to package the binaries
archives:
  - id: gimage
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

    # What to include in the archive
    files:
      - README.md
      - LICENSE*
      - CHANGELOG.md
      - docs/**/*

# Checksums - create checksums file for verification
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Snapshots - for development builds (not tagged releases)
snapshot:
  version_template: "{{ incpatch .Version }}-next"

# Changelog generation
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

# GitHub release configuration
release:
  github:
    owner: apresai
    name: gimage

  # Release notes template
  header: |
    ## gimage {{ .Version }}

    AI-powered image generation and processing CLI tool.

    ### Installation

    **macOS (Homebrew):**
    ```bash
    brew install apresai/tap/gimage
    ```

    **macOS/Linux (Direct Download):**
    ```bash
    # Download the appropriate binary for your platform
    # Extract and move to /usr/local/bin
    tar -xzf gimage_{{ .Version }}_Darwin_arm64.tar.gz
    sudo mv gimage /usr/local/bin/
    ```

    **Windows (Direct Download):**
    Download the .zip file, extract, and add to your PATH.

    **MCP Server (npm - for Claude Desktop):**
    ```bash
    npm install -g @apresai/gimage-mcp
    ```

  footer: |
    ### What's Next?

    Get started with image generation:
    ```bash
    # Set up API credentials
    gimage auth gemini

    # Generate your first image
    gimage generate "a sunset over mountains"
    ```

    For detailed documentation, visit: https://github.com/apresai/gimage

    **Full Changelog**: https://github.com/apresai/gimage/compare/{{ .PreviousTag }}...{{ .Tag }}

  # Don't create release if this is a pre-release
  prerelease: auto

  # Naming the release
  name_template: "v{{.Version}}"

# Homebrew tap configuration
brews:
  - ids:
      - gimage
      - gimage-deploy

    name: gimage

    # Repository for Homebrew formula
    repository:
      owner: apresai
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"

    # Commit message for formula update
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Version }}"

    # Formula template
    homepage: "https://github.com/apresai/gimage"
    description: "AI-powered image generation and processing CLI with AWS Lambda deployment manager"
    license: "MIT"

    # Installation steps
    install: |
      bin.install "gimage"
      bin.install "gimage-deploy"

    # Test that the installation worked
    test: |
      system "#{bin}/gimage", "--version"
      system "#{bin}/gimage-deploy", "--version"

    # Additional information
    caveats: |
      Two tools have been installed:

      1. gimage - Image generation and processing CLI
      2. gimage-deploy - AWS Lambda deployment manager

      To get started with gimage:

      1. Set up API credentials:
         gimage auth gemini

      2. Get your free Gemini API key:
         https://aistudio.google.com/app/apikey

      3. Generate your first image:
         gimage generate "a sunset over mountains"

      To deploy gimage as AWS Lambda:

         gimage-deploy deploy
         gimage-deploy tui  # Interactive UI

      For full documentation:
      https://github.com/apresai/gimage

# Announce the release (optional integrations)
announce:
  skip: false
