// Package gimage provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package gimage

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8w7a3PbNrZ/BcPdnXGylEzLdjfRTOeOkjiO2rR17aTtzibXgsgjCgkJsABoW83ov985",
	"ePAhkbLc9N7rL5ZEgAcH5/3ylyAWeSE4cK2C8ZdAgioEV2B+vKDJJfxegtL4KxZcAzdfaVFkLKaaCX74",
	"SQmOz+CO5kUGdmcCwfgkisIApBQyGCMo4mGFQQ5K0RSCcfArS/SS5KXSZA6kEIppdgPBOgxUvIScIri/",
	"S1gE4+BvhzWqh3ZVHZ4h/EuHdLBer8MgARVLViBywTiY8huasYRIezgpqKQ5aJAKD5lyDZLT7Myi+fBL",
	"njYv6aGRK5A3IImF2rzua8oySIgWpJAiBqUIy3Hlr7yvw0FZHCxu6+oAx1gdL38qQFL71pegkKIAqZll",
	"vEVq/GUD9guq4JuTAXC8e2JRJ0KSq2PyGVZBWJPHQlCHxVJoMfxUpEEY6FWBK0pLxlO8sWgi0D6pwo2Y",
	"t8IAeJkH4/+gfLI/8IGKaYafsRQFfoi8kKCU+cpvQOrgYxOf6r0tLIxAmFvTJGF4Js0uGtTQsoSwD72B",
	"KiBmCxY35SpsiskSWLrUwfgbFJRblPZg/CyK1hUmYv4JYm04hDLKJCR40Zo4oWNHherHrXdDy9GGsrb5",
	"GdMsm9P483Upsy5i21uTW5gvhfhM3l++JQshCRI1A8MGLjRe02NUE3apdaHGh4f5ihbFMBb5oYMShMFC",
	"yJzqYByUku0UALWN1FumNBELUu8xWgMSgSJNNFiu7dKWDTlfh0FO76b2zSNkSM64/1nhR6Wkq35+7KS/",
	"08stBsxx+Zol2/d8z9nvJRCzgbAEONIZZIvGZnFwNDo+Of3mX8+eR120lKDKTHcQ8tIuGIYCjZekJVn7",
	"UHGK4lfbnE1ChYHSVJeqy17gpZylYzwlbmOtzvWa0+EMNCQoOsZQtnW4ub51fwu6W8BRnrUg8RLiz47S",
	"NSYV+EOzcng/sdcd/H/p7E+vCnpd2MTtHZUpaGKXyYFwuhiSnDKuKeOKCMlShvrJFqiHxNkcSJ40KGlt",
	"7KcC8KMw9LyFedGmYI8h/rPmfgvQ7yXNmF5ZUAtaZjoYPzvdtJ6eVmhX3Bvk4GiACkmWLF2CJN+SOWgN",
	"8kmTQwgpp3csxxt79XW/KmQY15CCdCphRPa6pr2n1txcDd3IsRGZj11Mbqq/JdHHTs4bd9PL+L+MuF91",
	"nTDQRtCu++TwFSi8KxGlLkovj01N5Va+GlKWsoWXsjDQbLGwH0EYzPMNwfOb9qDxJqadNJei6CW497ib",
	"N8SXiF0kjJOC3UHWsgDf3C9Sj4WZLpDovKJZ677hs/tveLcN9TcSCyETxqkGdMlaFIMMFprEQvK2q2pr",
	"ZdR1wGr7gH//hQf0yNRdgCd7woVeSLqEqx1ib8dSJu7fvMKbd+8unFMhZkcDZ5MIbRMCfM7RhmSOr8Le",
	"SoPaCdSWQFQpxrZea5tzmOOI39cE7VMkK7aV5u/h9c6BYywBvbqYiwQ6HPJkSswKeuVSmTNJamG5+NLp",
	"QgrI68FoeDpYZFQtB56f1ULkFgoJNwxu7YZBC5h5xAfHw8g/h0EUHdUrJztXykxLumN9QZVuL7dMX+8V",
	"tnjIIaWY/V4XUuRFhwU7yyDHyAzJRm8EsowTvQTiQdanFiCKDEKi4U6H5JZqkDmVGJTn9O4t8BTNx1HU",
	"kMxGRtRz/Du406TxyKiqPx1x8kRoYUKJKrkCTQSmo7kobVTTxmQUOb2uUNvPZrYRvJCwAIlezG/d9mMd",
	"1rXG1T3rCi8BOoL3S8oTkRNcNDIsoZAiKWM2z4C4iJwcRHbN7G0FNCejRo7EuDZ47baeJotthlfBUTQ6",
	"ucM/wVYpwPAlYTlwZRKog1+nr969uXtzNj1/866FSQtKQTH0Qgj//eFD8s87/PP37ph7lXWYHHuuWTyk",
	"oPQSNIubocRSaCGBZkzZBSp19ZWzHNpM2dq+O4pw0ttl2d8AzfSOLI0WbEchoPbQ9IayjM5N/YELfR0L",
	"vmBpKU1mUvJ6uct1t2l1ZV2GWJDJ1JRsWAwbFQRrQFCTGsdiyAl3rYddBrovM/vpBiTNMn/idmK2NKRa",
	"GZlKJU3c1fzjFoPqvVuXvQGpOgs8k4sp8YtNWNHwaHi0n/Npp6V7J1zTtpdryBnvTI76wkkLZ1c8ier0",
	"tUFkQjUlB2g/VI4Ms3W1tu6yX178dHkbfX+eislkMvnx6v3y7H2KX8/wz4uXk38Ph8PuqEFTPGGX0N8j",
	"wJPqNVJB6xLE42uMhLcubSNkW21aUsYZTxsln66SYp2ZD+g8HvZwzVnyLhehWMohwdj8/eVbS9sMMw5H",
	"25DYaOibiOSMP+ksdqU2ylBaSJrCUB0PaU7/EJzeKlMCa6Dqkfyv3waT/I+BZcR9hTG08tfzlQbVK78s",
	"A4LbUPTszgaip6OT0bNnHc5lWxh7Mgl7yo5Uolu4u/T00pReH5yuucLI/QlboyLwv5fAPayy/bDsrlno",
	"c4v7JnyOSPemfA+gUU8CtUfidBXTrJ/PCxrrrnwH30Ktt+vkIBqekm/JkmaLkIyGEfmWJKKcZ9DSxGh4",
	"2pBuuyFo3bMZSA2j+p68zOePKZfvIbej1seuNoGCuJRMr67iJeSWuJOCfQ+rSdklI+hqvY2lpV4C166Q",
	"Tw6qyAWFBzeeUw23dIXEZtz69sRk4JzmiMZvg8nFdPB9kxDUnG17UYwvhG+j0diQwr14bgl5VRaFkOh4",
	"jXluWFS9LOfGeNJCgqLMGdkOjzMdFOIWZMWcOtkjlCfNejPeyO+dr8i5EGkG5NwEVGbvLyaMIpPp8AP/",
	"wP/2N/IaqC4lqA98QJ4+nUyJNYTn1RFPn47JSwlUe39BFlLkJs8ipTnUgR8NT8lrTPhQeKpzLDxOTuwB",
	"FvpFhTFCt/YyJKbDFZJYiiIkvr8VGrRdi8thYEHZYnvV7FAIygEmeZlpVmQVyrHgcSklcJ2t7NuvM7gz",
	"WYsPqPD1q0bIQagiVprDlrvE51fHpKj86vvLt8oRc9KStg/8pT8zNHkjcqdUoAjwGyYFx9x2gGckG3I6",
	"JK+FJDa1MmxOoMjEyuTC4QdOk4R4Id8Q8BtGm2I9/IDRZsZicCGjE84fpu/2l8jDeSbmhzll/PDt9OXZ",
	"j1dnJvRmOmvI+eRiGjTCXxfX2p4XpwWG88fDaHhs062lUWLbejCWU6jO9PZ+bpJbppckYYsF4INGLGUk",
	"/OlTp4CQNJbGT5+iFMxsk3TmRRBT+jp7NDuMTM7GxJh6VClrp8waCuoMlUMUREJqOI6PneTikvtqkXSl",
	"f7fJCLTZY0Xb2lLEeZJlzS4gleBVHEwBpKCYykDm1U+QVEhRasZBWYZXb08T35VytAys9QWlX4hktf8A",
	"gC1usTtIrttNTFXmOZUrlCnPpVY4e0Oz0khe87X/VF2CVnRx5MKLRp+87mPXbeu+DvM67AY7cjFzE2yj",
	"fV4Drvyrq95X3Z1np73Ajztwdi36bYxt/cmhbH/cmbrHKhhH6/XH9XrvuYhW/3vd9qpaltBw0waFURTt",
	"we0Hnd0/k7HVB607meswOLGodJ1QoXzYGMVZh8HpPq+0Z1sMKSvh7DElpvmSokRanIOP+NphJR29pqnS",
	"bMrrcqCEpIybqYpRex9yUPQ2TqScbfrZNQMVaM14Wtkl0xucjcl3F2fnh7/C/KJuG270C/2C81HSHP4E",
	"gbyyBbMxmT07nZGDVIiEzGlGeWzXLyEWeQ48gQT3RIPn0cyETLcwD8nseTR4fmofFJJx3WFXPA2mLoT7",
	"84YFL3Xd6KXWfHvD0spwVjGBraFUlqVSy7osYLPOCuLz046g1YeoyPFbmF+LQrPcVRtrBH5yTz1pmgdX",
	"kKwJ2DAPhiGDZtrUsid7a/pmp/3/WNk3hiE6BrCM+HveQEJUGaOuLcosW/1/6Xuln3WP1ap5HXpWum6n",
	"p3aounXQlabPQd8C8EbQYQVhO+Jwz71aFzydjcmFkNrYgh9B3wr5mZxLWixZrMiBsm8qoiXlqqASeLwy",
	"2jr7VKSzED8gdYaBHGRCqVVIuOjYn7LFbFyDNrSKl5SngLGlGb3IWM4Qy1hkQqqwAwj6wdmYGAt0kIsE",
	"JEcdcPcKbYkOpDF2yr6i2WKBiGpz/juappC4nOI12sXXLswZkNk8R+AvmM5p0WleDN2/3rpocY3611Jr",
	"z1QtDC33MifbFqQuX7RnDYxBMLUhcW1iib6zkbKdZzdrLq7it3GEgfsgM9Ia23isVsQg+WiMSCPrbPSJ",
	"e00Jxn39dgTzBEokxJrytMyodFmDTai9eXFG5GU1IFCZjzvUqxVqVXtcgIiFSZo9uIMojAhT9VSBWFjQ",
	"Tqkx/ERQNiqdjcmrumPWBtWllVIUX6+SMSDZrz3BGiTHw+2qw6GpHq3Iv1NXrKOtkwITYJsZipX5fIjC",
	"NGZuHqm2SFEUj0VXkHGNSNixrldXqtZ5r774WQvUjMnUK6FRFVt9anbmfSrcrHc1y1BOq34QCWSKTHwP",
	"0amWfWFMZt2zCzNy4NrPT8LGnvsmMWYIusJgTGY90xeoizvHLzY2bM1fzOzlvMA4H1vZDeulZmPnhk2H",
	"rar2clfksn0hV2D5UEbRcUxOj0bfv7BGw8bKGL1s9pNs8whftg2kUoNqNJk8zCcdtsRz+OvtCU1uMLFJ",
	"2sZk4p7aPMxOmrZqEm5ap39kZWtCpTVnEtSjI8Gi1KU0DXsSY65ijlxkK5P9UqmCHRmIn7Y4Gfl5h9Z4",
	"gps62JwLMPrHfNO8vvWVedYeL6puXOHbN6XyAAO5OQz1lxnJJmddiNW6oe1Y1DMvB41W8ZPOBM2GUHUZ",
	"ZnQSdsV5fd1k/Fy8jq++wy+v3mdnP/9yeTLKf/z8zx+e//zqdvJqmZ5Pfv10+Zzemle+u3x/eiY/f5em",
	"6bffBu32pm9VVlWg0cm61b9tcNJqWH3PRh16n3uOopNndSd6Zz/ZH/9nOr5tYK2+b/Pio+j5v45OR9XN",
	"EbsHSNuePtHbxcfhFSsf1vBexnc5PawdZN1wcQ7SDpnYeZiuaNLM9k8upsRuNG0SNxvDTLWkPWJjHOAl",
	"6FJy5ec2xWJcez8D64Bh/AfmvzJopkg96POk5cx2b9wy9HYOyaAcfLVFoFl2XQ8BtQ1+luE1FGlNDnkt",
	"8dNOD5gv8uNEjZGfrRbH2g9nXguebZSvfCSCCw/GZGPSal909taojemwDpW6ctNSTBF/Ylu+LQj7jyYN",
	"YbaPnSC7Cn5vnOd6L81CKtzR2Df5Ua7dTIQN8pYsXQ58SfAt5fEfQqGNRAlhPHWR3pTXU/0+EuodOMJF",
	"P5iDKmoiOoEa4sW4Q6gt3l8fu1gPd80Q4bb0OMq4AM3HJPdkQ/vORu2oZrR6Kuga+nG7Ou7H6yh6tp2m",
	"dXqfHZGRd5PPRw/J3dojOI8ze7N68Tj8lONmpYDVf3nW7dBdyZz939ReDbfN07p+uiLUN2J839q2VZ3u",
	"njnt8AlMNDyduREZ21c5OI3+YfOS0TCaVRMzbnEU+dVoODJv/l5SqV2dkhyMTv/R5aQMll+vzhaVa7XV",
	"SbBU0IIgfq3ozQ0KjXq1uE9jGx0MJM6uQ0+7zzRzRb1VxwdoXGsW6nEqnJHSx6Fvli2VOjhu9GmYGYGS",
	"6OlN63xrSMJPiZgITkKR0dj1HleilM15EMwnnmxNfuCuAS3YgCVDuIO41IA/h6UaAFV6cLQR+xdSYDiy",
	"9R/MIqYZSeAGMlHkwDU5uJr8QDJ83D50fHhoni6F0uPjKIqC9cfq8l/2H3+qx7Qa4fM2Ypb9jXZ0a0LB",
	"QWiQfBvCVkO7C4LtIG+/3AySTDhTDZ+7F124tP64/p8AAAD//4boyVqeQgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
