// Package gimage provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package gimage

// Defines values for BatchOperationOperation.
const (
	Compress BatchOperationOperation = "compress"
	Convert  BatchOperationOperation = "convert"
	Crop     BatchOperationOperation = "crop"
	Resize   BatchOperationOperation = "resize"
	Scale    BatchOperationOperation = "scale"
)

// Defines values for BatchResponseStatus.
const (
	Completed  BatchResponseStatus = "completed"
	Failed     BatchResponseStatus = "failed"
	Processing BatchResponseStatus = "processing"
)

// Defines values for CompressRequestFormat.
const (
	CompressRequestFormatJpeg CompressRequestFormat = "jpeg"
	CompressRequestFormatJpg  CompressRequestFormat = "jpg"
	CompressRequestFormatPng  CompressRequestFormat = "png"
	CompressRequestFormatWebp CompressRequestFormat = "webp"
)

// Defines values for CompressRequestResponseFormat.
const (
	CompressRequestResponseFormatBase64 CompressRequestResponseFormat = "base64"
	CompressRequestResponseFormatS3Url  CompressRequestResponseFormat = "s3_url"
)

// Defines values for ConvertRequestResponseFormat.
const (
	ConvertRequestResponseFormatBase64 ConvertRequestResponseFormat = "base64"
	ConvertRequestResponseFormatS3Url  ConvertRequestResponseFormat = "s3_url"
)

// Defines values for ConvertRequestTargetFormat.
const (
	ConvertRequestTargetFormatBmp  ConvertRequestTargetFormat = "bmp"
	ConvertRequestTargetFormatGif  ConvertRequestTargetFormat = "gif"
	ConvertRequestTargetFormatJpeg ConvertRequestTargetFormat = "jpeg"
	ConvertRequestTargetFormatJpg  ConvertRequestTargetFormat = "jpg"
	ConvertRequestTargetFormatPng  ConvertRequestTargetFormat = "png"
	ConvertRequestTargetFormatTif  ConvertRequestTargetFormat = "tif"
	ConvertRequestTargetFormatTiff ConvertRequestTargetFormat = "tiff"
	ConvertRequestTargetFormatWebp ConvertRequestTargetFormat = "webp"
)

// Defines values for CropRequestResponseFormat.
const (
	CropRequestResponseFormatBase64 CropRequestResponseFormat = "base64"
	CropRequestResponseFormatS3Url  CropRequestResponseFormat = "s3_url"
)

// Defines values for GenerateRequestModel.
const (
	Gemini20FlashPreviewImageGeneration GenerateRequestModel = "gemini-2.0-flash-preview-image-generation"
	Gemini25FlashImage                  GenerateRequestModel = "gemini-2.5-flash-image"
	Imagen30Generate001                 GenerateRequestModel = "imagen-3.0-generate-001"
	Imagen40FastGenerate001             GenerateRequestModel = "imagen-4.0-fast-generate-001"
	Imagen40Generate001                 GenerateRequestModel = "imagen-4.0-generate-001"
	Imagen40UltraGenerate001            GenerateRequestModel = "imagen-4.0-ultra-generate-001"
)

// Defines values for GenerateRequestResponseFormat.
const (
	GenerateRequestResponseFormatBase64 GenerateRequestResponseFormat = "base64"
	GenerateRequestResponseFormatS3Url  GenerateRequestResponseFormat = "s3_url"
)

// Defines values for GenerateRequestStyle.
const (
	Anime          GenerateRequestStyle = "anime"
	Artistic       GenerateRequestStyle = "artistic"
	Photorealistic GenerateRequestStyle = "photorealistic"
)

// Defines values for HealthResponseApis.
const (
	Available     HealthResponseApis = "available"
	NotConfigured HealthResponseApis = "not_configured"
	Unavailable   HealthResponseApis = "unavailable"
)

// Defines values for HealthResponseStatus.
const (
	Degraded  HealthResponseStatus = "degraded"
	Healthy   HealthResponseStatus = "healthy"
	Unhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for ResizeRequestResponseFormat.
const (
	ResizeRequestResponseFormatBase64 ResizeRequestResponseFormat = "base64"
	ResizeRequestResponseFormatS3Url  ResizeRequestResponseFormat = "s3_url"
)

// Defines values for ScaleRequestResponseFormat.
const (
	ScaleRequestResponseFormatBase64 ScaleRequestResponseFormat = "base64"
	ScaleRequestResponseFormatS3Url  ScaleRequestResponseFormat = "s3_url"
)

// BatchOperation defines model for BatchOperation.
type BatchOperation struct {
	// Image Base64-encoded image or S3 key
	Image string `json:"image"`

	// Operation Operation type
	Operation BatchOperationOperation `json:"operation"`

	// Params Operation-specific parameters
	Params map[string]interface{} `json:"params"`
}

// BatchOperationOperation Operation type
type BatchOperationOperation string

// BatchRequest defines model for BatchRequest.
type BatchRequest struct {
	// CallbackUrl Optional webhook URL for completion notification
	CallbackUrl *string `json:"callback_url,omitempty"`

	// Operations List of operations to perform
	Operations []BatchOperation `json:"operations"`
}

// BatchResponse defines model for BatchResponse.
type BatchResponse struct {
	// BatchId Unique batch identifier
	BatchId *string `json:"batch_id,omitempty"`

	// Results Results for each operation
	Results *[]ImageResponse `json:"results,omitempty"`

	// Status Batch processing status
	Status *BatchResponseStatus `json:"status,omitempty"`

	// StatusUrl URL to check batch status
	StatusUrl *string `json:"status_url,omitempty"`
}

// BatchResponseStatus Batch processing status
type BatchResponseStatus string

// CompressRequest defines model for CompressRequest.
type CompressRequest struct {
	// Format Target format (optional, maintains original if not specified)
	Format *CompressRequestFormat `json:"format,omitempty"`

	// Image Base64-encoded image or S3 key
	Image string `json:"image"`

	// Quality Compression quality (1-100, higher = better)
	Quality        *int                           `json:"quality,omitempty"`
	ResponseFormat *CompressRequestResponseFormat `json:"response_format,omitempty"`
}

// CompressRequestFormat Target format (optional, maintains original if not specified)
type CompressRequestFormat string

// CompressRequestResponseFormat defines model for CompressRequest.ResponseFormat.
type CompressRequestResponseFormat string

// ConvertRequest defines model for ConvertRequest.
type ConvertRequest struct {
	// Image Base64-encoded image or S3 key
	Image          string                        `json:"image"`
	ResponseFormat *ConvertRequestResponseFormat `json:"response_format,omitempty"`

	// TargetFormat Desired output format
	TargetFormat ConvertRequestTargetFormat `json:"target_format"`
}

// ConvertRequestResponseFormat defines model for ConvertRequest.ResponseFormat.
type ConvertRequestResponseFormat string

// ConvertRequestTargetFormat Desired output format
type ConvertRequestTargetFormat string

// CropRequest defines model for CropRequest.
type CropRequest struct {
	// Height Crop height in pixels
	Height int `json:"height"`

	// Image Base64-encoded image or S3 key
	Image          string                     `json:"image"`
	ResponseFormat *CropRequestResponseFormat `json:"response_format,omitempty"`

	// Width Crop width in pixels
	Width int `json:"width"`

	// X X coordinate of top-left corner
	X int `json:"x"`

	// Y Y coordinate of top-left corner
	Y int `json:"y"`
}

// CropRequestResponseFormat defines model for CropRequest.ResponseFormat.
type CropRequestResponseFormat string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code HTTP status code
	Code *int `json:"code,omitempty"`

	// Error Error type
	Error *string `json:"error,omitempty"`

	// Message Detailed error message
	Message *string `json:"message,omitempty"`
}

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	// Model AI model to use for generation
	Model *GenerateRequestModel `json:"model,omitempty"`

	// NegativePrompt Elements to avoid in the image
	NegativePrompt *string `json:"negative_prompt,omitempty"`

	// Prompt Text description of the image to generate
	Prompt string `json:"prompt"`

	// ResponseFormat Preferred response format
	ResponseFormat *GenerateRequestResponseFormat `json:"response_format,omitempty"`

	// Seed Random seed for reproducible results (0 for random)
	Seed *int64 `json:"seed,omitempty"`

	// Size Image dimensions (WIDTHxHEIGHT)
	Size *string `json:"size,omitempty"`

	// Style Image style/aesthetic
	Style *GenerateRequestStyle `json:"style,omitempty"`
}

// GenerateRequestModel AI model to use for generation
type GenerateRequestModel string

// GenerateRequestResponseFormat Preferred response format
type GenerateRequestResponseFormat string

// GenerateRequestStyle Image style/aesthetic
type GenerateRequestStyle string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Apis Status of AI services
	Apis *map[string]HealthResponseApis `json:"apis,omitempty"`

	// Status Overall service status
	Status *HealthResponseStatus `json:"status,omitempty"`

	// Version API version
	Version *string `json:"version,omitempty"`
}

// HealthResponseApis defines model for HealthResponse.Apis.
type HealthResponseApis string

// HealthResponseStatus Overall service status
type HealthResponseStatus string

// ImageResponse defines model for ImageResponse.
type ImageResponse struct {
	// Format Image format
	Format *string `json:"format,omitempty"`

	// Height Image height in pixels
	Height *int `json:"height,omitempty"`

	// Image Base64-encoded image data (for small images)
	Image *string `json:"image,omitempty"`

	// Metadata Additional metadata
	Metadata *map[string]string `json:"metadata,omitempty"`

	// S3Key S3 key for chaining operations
	S3Key *string `json:"s3_key,omitempty"`

	// S3Url Presigned S3 URL (for large images, valid 60 min)
	S3Url *string `json:"s3_url,omitempty"`

	// SizeBytes Image file size in bytes
	SizeBytes *int64 `json:"size_bytes,omitempty"`

	// Width Image width in pixels
	Width *int `json:"width,omitempty"`
}

// ResizeRequest defines model for ResizeRequest.
type ResizeRequest struct {
	// Height Target height in pixels
	Height int `json:"height"`

	// Image Base64-encoded image or S3 key
	Image          string                       `json:"image"`
	ResponseFormat *ResizeRequestResponseFormat `json:"response_format,omitempty"`

	// Width Target width in pixels
	Width int `json:"width"`
}

// ResizeRequestResponseFormat defines model for ResizeRequest.ResponseFormat.
type ResizeRequestResponseFormat string

// ScaleRequest defines model for ScaleRequest.
type ScaleRequest struct {
	// Factor Scaling factor (0.5 = half, 2.0 = double)
	Factor float64 `json:"factor"`

	// Image Base64-encoded image or S3 key
	Image          string                      `json:"image"`
	ResponseFormat *ScaleRequestResponseFormat `json:"response_format,omitempty"`
}

// ScaleRequestResponseFormat defines model for ScaleRequest.ResponseFormat.
type ScaleRequestResponseFormat string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// BatchProcessJSONRequestBody defines body for BatchProcess for application/json ContentType.
type BatchProcessJSONRequestBody = BatchRequest

// CompressImageJSONRequestBody defines body for CompressImage for application/json ContentType.
type CompressImageJSONRequestBody = CompressRequest

// ConvertImageJSONRequestBody defines body for ConvertImage for application/json ContentType.
type ConvertImageJSONRequestBody = ConvertRequest

// CropImageJSONRequestBody defines body for CropImage for application/json ContentType.
type CropImageJSONRequestBody = CropRequest

// GenerateImageJSONRequestBody defines body for GenerateImage for application/json ContentType.
type GenerateImageJSONRequestBody = GenerateRequest

// ResizeImageJSONRequestBody defines body for ResizeImage for application/json ContentType.
type ResizeImageJSONRequestBody = ResizeRequest

// ScaleImageJSONRequestBody defines body for ScaleImage for application/json ContentType.
type ScaleImageJSONRequestBody = ScaleRequest
